# Generated by Django 2.1.2 on 2018-10-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortens',
            name='origin',
            field=models.CharField(db_index=True, max_length=1000),
        ),
    ]
